const teams = [
  { id: 1, name: "Punjab Kings", shortName: "PBKS", logo: "images/logos/pbks.png", played: 8, won: 6, lost: 1, points: 13, nrr: "+1.043" },
  { id: 2, name: "Royal Challengers Bengaluru", shortName: "RCB", logo: "images/logos/rcb.png", played: 9, won: 6, lost: 3, points: 12, nrr: "+1.420" },
  { id: 3, name: "Sunrisers Hyderabad", shortName: "SRH", logo: "images/logos/srh.png", played: 9, won: 6, lost: 3, points: 12, nrr: "+0.832" },
  { id: 4, name: "Rajasthan Royals", shortName: "RR", logo: "images/logos/rr.png", played: 10, won: 6, lost: 4, points: 12, nrr: "+0.510" },
  { id: 5, name: "Gujarat Titans", shortName: "GT", logo: "images/logos/gt.png", played: 9, won: 5, lost: 4, points: 10, nrr: "-0.192" },
  { id: 6, name: "Chennai Super Kings", shortName: "CSK", logo: "images/logos/csk.png", played: 9, won: 4, lost: 5, points: 8, nrr: "+0.005" },
  { id: 7, name: "Delhi Capitals", shortName: "DC", logo: "images/logos/dc.png", played: 9, won: 4, lost: 5, points: 8, nrr: "-0.895" },
  { id: 8, name: "Kolkata Knight Riders", shortName: "KKR", logo: "images/logos/kkr.png", played: 8, won: 2, lost: 5, points: 5, nrr: "-0.751" },
  { id: 9, name: "Mumbai Indians", shortName: "MI", logo: "images/logos/mi.png", played: 9, won: 2, lost: 7, points: 4, nrr: "-0.803" },
  { id: 10, name: "Lucknow Super Giants", shortName: "LSG", logo: "images/logos/lsg.png", played: 8, won: 2, lost: 6, points: 4, nrr: "-1.106" }
];

const players = [
  { id: 1, name: "KL Rahul", team: "DC", runs: 433, wickets: 0, matches: 9 },
  { id: 2, name: "Abhishek Sharma", team: "SRH", runs: 425, wickets: 0, matches: 9 },
  { id: 3, name: "Heinrich Klaasen", team: "SRH", runs: 414, wickets: 0, matches: 9 },
  { id: 4, name: "Vaibhav Sooryavanshi", team: "RR", runs: 404, wickets: 0, matches: 10 },
  { id: 5, name: "Virat Kohli", team: "RCB", runs: 379, wickets: 0, matches: 9 },
  { id: 6, name: "Bhuvneshwar Kumar", team: "RCB", runs: 10, wickets: 17, matches: 9 },
  { id: 7, name: "Eshan Malinga", team: "SRH", runs: 5, wickets: 15, matches: 9 },
  { id: 8, name: "Jofra Archer", team: "RR", runs: 20, wickets: 14, matches: 10 },
  { id: 9, name: "Anshul Kamboj", team: "CSK", runs: 15, wickets: 14, matches: 9 },
  { id: 10, name: "Kagiso Rabada", team: "GT", runs: 30, wickets: 14, matches: 9 }
];

const matches = [
  { id: 24, team1: "MI", team2: "PBKS", date: "2026-04-16", venue: "Wankhede Stadium", result: "Kings won by 7 wickets" },
  { id: 25, team1: "GT", team2: "KKR", date: "2026-04-17", venue: "Narendra Modi Stadium", result: "Titans won by 5 wickets" },
  { id: 26, team1: "RCB", team2: "DC", date: "2026-04-18", venue: "Chinnaswamy Stadium", result: "Capitals won by 6 wickets" },
  { id: 27, team1: "SRH", team2: "CSK", date: "2026-04-18", venue: "Rajiv Gandhi Stadium", result: "Sunrisers won by 10 runs" },
  { id: 28, team1: "KKR", team2: "RR", date: "2026-04-19", venue: "Eden Gardens", result: "Knight Riders won by 4 wickets" },
  { id: 29, team1: "PBKS", team2: "LSG", date: "2026-04-19", venue: "Mullanpur", result: "Kings won by 54 runs" },
  { id: 30, team1: "GT", team2: "MI", date: "2026-04-20", venue: "Narendra Modi Stadium", result: "Indians won by 99 runs" },
  { id: 31, team1: "SRH", team2: "DC", date: "2026-04-21", venue: "Rajiv Gandhi Stadium", result: "Sunrisers won by 47 runs" },
  { id: 32, team1: "LSG", team2: "RR", date: "2026-04-22", venue: "Ekana Stadium", result: "Royals won by 40 runs" },
  { id: 33, team1: "MI", team2: "CSK", date: "2026-04-23", venue: "Wankhede Stadium", result: "Super Kings won by 103 runs" },
  { id: 34, team1: "RCB", team2: "GT", date: "2026-04-24", venue: "Chinnaswamy Stadium", result: "Royal Challengers won by 5 wickets" },
  { id: 35, team1: "DC", team2: "PBKS", date: "2026-04-25", venue: "Arun Jaitley Stadium", result: "Kings won by 6 wickets" },
  { id: 36, team1: "RR", team2: "SRH", date: "2026-04-25", venue: "Sawai Mansingh Stadium", result: "Sunrisers won by 5 wickets" },
  { id: 37, team1: "CSK", team2: "GT", date: "2026-04-26", venue: "Chepauk Stadium", result: "Titans won by 8 wickets" },
  { id: 38, team1: "LSG", team2: "KKR", date: "2026-04-26", venue: "Ekana Stadium", result: "Knight Riders won the Super Over" },
  { id: 39, team1: "DC", team2: "RCB", date: "2026-04-27", venue: "Arun Jaitley Stadium", result: "Royal Challengers won by 9 wickets" },
  { id: 40, team1: "PBKS", team2: "RR", date: "2026-04-28", venue: "Mullanpur", result: "Royals won by 6 wickets" },
  { id: 41, team1: "MI", team2: "SRH", date: "2026-04-29", venue: "Wankhede Stadium", result: "Sunrisers won by 6 wickets" },
  { id: 42, team1: "GT", team2: "RCB", date: "2026-04-30", venue: "Narendra Modi Stadium", result: "Titans won by 4 wickets" },
  { id: 43, team1: "RR", team2: "DC", date: "2026-05-01", venue: "Sawai Mansingh Stadium", result: "Capitals won by 7 wickets" },
  { id: 44, team1: "CSK", team2: "MI", date: "2026-05-02", venue: "Chepauk Stadium", result: "Super Kings won by 8 wickets" },
  { id: 45, team1: "SRH", team2: "KKR", date: "2026-05-03", venue: "Rajiv Gandhi Intl Stadium", result: "Upcoming 3:30 PM" },
  { id: 46, team1: "GT", team2: "PBKS", date: "2026-05-03", venue: "Narendra Modi Stadium", result: "Upcoming 7:30 PM" },
  { id: 47, team1: "MI", team2: "LSG", date: "2026-05-04", venue: "Wankhede Stadium", result: "Upcoming 7:30 PM" },
  { id: 48, team1: "DC", team2: "CSK", date: "2026-05-05", venue: "Arun Jaitley Stadium", result: "Upcoming 7:30 PM" },
  { id: 49, team1: "SRH", team2: "PBKS", date: "2026-05-06", venue: "Rajiv Gandhi Intl Stadium", result: "Upcoming 7:30 PM" },
  { id: 50, team1: "LSG", team2: "RCB", date: "2026-05-07", venue: "Ekana Cricket Stadium", result: "Upcoming 7:30 PM" },
  { id: 51, team1: "DC", team2: "KKR", date: "2026-05-08", venue: "Arun Jaitley Stadium", result: "Upcoming 7:30 PM" },
  { id: 52, team1: "RR", team2: "GT", date: "2026-05-09", venue: "Sawai Mansingh Stadium", result: "Upcoming 7:30 PM" },
  { id: 53, team1: "CSK", team2: "LSG", date: "2026-05-10", venue: "MA Chidambaram Stadium", result: "Upcoming 3:30 PM" },
  { id: 54, team1: "RCB", team2: "MI", date: "2026-05-10", venue: "SVNS Intl Stadium", result: "Upcoming 7:30 PM" },
  { id: 55, team1: "PBKS", team2: "DC", date: "2026-05-11", venue: "HPCA Stadium", result: "Upcoming 7:30 PM" },
  { id: 56, team1: "GT", team2: "SRH", date: "2026-05-12", venue: "Narendra Modi Stadium", result: "Upcoming 7:30 PM" },
  { id: 57, team1: "RCB", team2: "KKR", date: "2026-05-13", venue: "SVNS Intl Stadium", result: "Upcoming 7:30 PM" },
  { id: 58, team1: "PBKS", team2: "MI", date: "2026-05-14", venue: "HPCA Stadium", result: "Upcoming 7:30 PM" },
  { id: 59, team1: "LSG", team2: "CSK", date: "2026-05-15", venue: "Ekana Cricket Stadium", result: "Upcoming 7:30 PM" },
  { id: 60, team1: "KKR", team2: "GT", date: "2026-05-16", venue: "Eden Gardens", result: "Upcoming 7:30 PM" },
  { id: 61, team1: "PBKS", team2: "RCB", date: "2026-05-17", venue: "HPCA Stadium", result: "Upcoming 3:30 PM" },
  { id: 62, team1: "DC", team2: "RR", date: "2026-05-17", venue: "Arun Jaitley Stadium", result: "Upcoming 7:30 PM" },
  { id: 63, team1: "CSK", team2: "SRH", date: "2026-05-18", venue: "MA Chidambaram Stadium", result: "Upcoming 7:30 PM" },
  { id: 64, team1: "RR", team2: "LSG", date: "2026-05-19", venue: "Sawai Mansingh Stadium", result: "Upcoming 7:30 PM" },
  { id: 65, team1: "KKR", team2: "MI", date: "2026-05-20", venue: "Eden Gardens", result: "Upcoming 7:30 PM" },
  { id: 66, team1: "GT", team2: "CSK", date: "2026-05-21", venue: "Narendra Modi Stadium", result: "Upcoming 7:30 PM" },
  { id: 67, team1: "SRH", team2: "RCB", date: "2026-05-22", venue: "Rajiv Gandhi Intl Stadium", result: "Upcoming 7:30 PM" },
  { id: 68, team1: "LSG", team2: "PBKS", date: "2026-05-23", venue: "Ekana Cricket Stadium", result: "Upcoming 7:30 PM" },
  { id: 69, team1: "MI", team2: "RR", date: "2026-05-24", venue: "Wankhede Stadium", result: "Upcoming 3:30 PM" },
  { id: 70, team1: "KKR", team2: "DC", date: "2026-05-24", venue: "Eden Gardens", result: "Upcoming 7:30 PM" },
  { id: 71, team1: "TBD", team2: "TBD", date: "2026-05-26", venue: "TBD", result: "Playoff 1" },
  { id: 72, team1: "TBD", team2: "TBD", date: "2026-05-27", venue: "TBD", result: "Eliminator" },
  { id: 73, team1: "TBD", team2: "TBD", date: "2026-05-29", venue: "TBD", result: "Playoff 2" },
  { id: 74, team1: "TBD", team2: "TBD", date: "2026-05-31", venue: "TBD", result: "Final" }
];

const stockPlayers = [
  // CSK
  { id: 1, name: "Ruturaj Gaikwad", team: "CSK", category: "Indian", cost: 8 },
  { id: 2, name: "MS Dhoni", team: "CSK", category: "Indian", cost: 8 },
  { id: 3, name: "Sanju Samson", team: "CSK", category: "Indian", cost: 8 },
  { id: 4, name: "Shivam Dube", team: "CSK", category: "Indian", cost: 8 },
  { id: 5, name: "Khaleel Ahmed", team: "CSK", category: "Indian", cost: 8 },
  { id: 6, name: "Sarfaraz Khan", team: "CSK", category: "Indian", cost: 8 },
  { id: 7, name: "Akash Madhwal", team: "CSK", category: "Indian", cost: 8 },
  { id: 8, name: "Urvil Patel", team: "CSK", category: "Indian", cost: 8 },
  { id: 9, name: "Rahul Chahar", team: "CSK", category: "Indian", cost: 8 },
  { id: 10, name: "Shreyas Gopal", team: "CSK", category: "Indian", cost: 8 },
  { id: 11, name: "Anshul Kamboj", team: "CSK", category: "Indian", cost: 10 },
  { id: 12, name: "Jamie Overton", team: "CSK", category: "Overseas", cost: 8 },
  { id: 13, name: "Dewald Brevis", team: "CSK", category: "Overseas", cost: 8 },
  { id: 14, name: "Akeal Hosein", team: "CSK", category: "Overseas", cost: 8 },
  { id: 15, name: "Matthew Short", team: "CSK", category: "Overseas", cost: 8 },
  { id: 16, name: "Spencer Johnson", team: "CSK", category: "Overseas", cost: 8 },
  
  // DC
  { id: 17, name: "KL Rahul", team: "DC", category: "Indian", cost: 10 },
  { id: 18, name: "Prithvi Shaw", team: "DC", category: "Indian", cost: 8 },
  { id: 19, name: "Karun Nair", team: "DC", category: "Indian", cost: 8 },
  { id: 20, name: "Axar Patel", team: "DC", category: "Indian", cost: 8 },
  { id: 21, name: "Tristan Stubbs", team: "DC", category: "Overseas", cost: 8 },
  { id: 22, name: "David Miller", team: "DC", category: "Overseas", cost: 8 },
  { id: 23, name: "Pathum Nissanka", team: "DC", category: "Overseas", cost: 8 },
  { id: 24, name: "Kuldeep Yadav", team: "DC", category: "Indian", cost: 8 },
  { id: 25, name: "Mukesh Kumar", team: "DC", category: "Indian", cost: 8 },
  { id: 26, name: "T Natarajan", team: "DC", category: "Indian", cost: 8 },
  { id: 27, name: "Sameer Rizvi", team: "DC", category: "Indian", cost: 8 },
  { id: 28, name: "Ashutosh Sharma", team: "DC", category: "Indian", cost: 8 },
  { id: 29, name: "Abishek Porel", team: "DC", category: "Indian", cost: 8 },
  { id: 30, name: "Mitchell Starc", team: "DC", category: "Overseas", cost: 8 },
  { id: 31, name: "Lungi Ngidi", team: "DC", category: "Overseas", cost: 8 },
  { id: 32, name: "Dushmantha Chameera", team: "DC", category: "Overseas", cost: 8 },

  // GT
  { id: 33, name: "Shubman Gill", team: "GT", category: "Indian", cost: 8 },
  { id: 34, name: "Sai Sudharsan", team: "GT", category: "Indian", cost: 8 },
  { id: 35, name: "Jos Buttler", team: "GT", category: "Overseas", cost: 8 },
  { id: 36, name: "Washington Sundar", team: "GT", category: "Indian", cost: 8 },
  { id: 37, name: "Rahul Tewatia", team: "GT", category: "Indian", cost: 8 },
  { id: 38, name: "Shahrukh Khan", team: "GT", category: "Indian", cost: 8 },
  { id: 39, name: "Kagiso Rabada", team: "GT", category: "Overseas", cost: 10 },
  { id: 40, name: "Mohammed Siraj", team: "GT", category: "Indian", cost: 8 },
  { id: 41, name: "Rashid Khan", team: "GT", category: "Overseas", cost: 8 },
  { id: 42, name: "Glenn Phillips", team: "GT", category: "Overseas", cost: 8 },
  { id: 43, name: "Prasidh Krishna", team: "GT", category: "Indian", cost: 8 },
  { id: 44, name: "Jason Holder", team: "GT", category: "Overseas", cost: 8 },
  { id: 45, name: "Sai Kishore", team: "GT", category: "Indian", cost: 8 },
  { id: 46, name: "Jayant Yadav", team: "GT", category: "Indian", cost: 8 },
  { id: 47, name: "Kumar Kushagra", team: "GT", category: "Indian", cost: 8 },

  // KKR
  { id: 48, name: "Ajinkya Rahane", team: "KKR", category: "Indian", cost: 8 },
  { id: 49, name: "Rinku Singh", team: "KKR", category: "Indian", cost: 8 },
  { id: 50, name: "Manish Pandey", team: "KKR", category: "Indian", cost: 8 },
  { id: 51, name: "Rahul Tripathi", team: "KKR", category: "Indian", cost: 8 },
  { id: 52, name: "Sunil Narine", team: "KKR", category: "Overseas", cost: 8 },
  { id: 53, name: "Cameron Green", team: "KKR", category: "Overseas", cost: 8 },
  { id: 54, name: "Rovman Powell", team: "KKR", category: "Overseas", cost: 8 },
  { id: 55, name: "Varun Chakaravarthy", team: "KKR", category: "Indian", cost: 8 },
  { id: 56, name: "Matheesha Pathirana", team: "KKR", category: "Overseas", cost: 8 },
  { id: 57, name: "Umran Malik", team: "KKR", category: "Indian", cost: 8 },
  { id: 58, name: "Vaibhav Arora", team: "KKR", category: "Indian", cost: 8 },
  { id: 59, name: "Navdeep Saini", team: "KKR", category: "Indian", cost: 8 },
  { id: 60, name: "Finn Allen", team: "KKR", category: "Overseas", cost: 8 },
  { id: 61, name: "Rachin Ravindra", team: "KKR", category: "Overseas", cost: 8 },
  { id: 62, name: "Ramandeep Singh", team: "KKR", category: "Indian", cost: 8 },

  // LSG
  { id: 63, name: "Rishabh Pant", team: "LSG", category: "Indian", cost: 8 },
  { id: 64, name: "Aiden Markram", team: "LSG", category: "Overseas", cost: 8 },
  { id: 65, name: "Josh Inglis", team: "LSG", category: "Overseas", cost: 8 },
  { id: 66, name: "Nicholas Pooran", team: "LSG", category: "Overseas", cost: 8 },
  { id: 67, name: "Mitchell Marsh", team: "LSG", category: "Overseas", cost: 8 },
  { id: 68, name: "Wanindu Hasaranga", team: "LSG", category: "Overseas", cost: 8 },
  { id: 69, name: "Ayush Badoni", team: "LSG", category: "Indian", cost: 8 },
  { id: 70, name: "Abdul Samad", team: "LSG", category: "Indian", cost: 8 },
  { id: 71, name: "Mohammad Shami", team: "LSG", category: "Indian", cost: 8 },
  { id: 72, name: "Avesh Khan", team: "LSG", category: "Indian", cost: 8 },
  { id: 73, name: "Anrich Nortje", team: "LSG", category: "Overseas", cost: 8 },
  { id: 74, name: "Mayank Yadav", team: "LSG", category: "Indian", cost: 8 },
  { id: 75, name: "Mohsin Khan", team: "LSG", category: "Indian", cost: 8 },
  { id: 76, name: "Arjun Tendulkar", team: "LSG", category: "Indian", cost: 8 },
  { id: 77, name: "Shahbaz Ahamad", team: "LSG", category: "Indian", cost: 8 },

  // MI
  { id: 78, name: "Rohit Sharma", team: "MI", category: "Indian", cost: 8 },
  { id: 79, name: "Suryakumar Yadav", team: "MI", category: "Indian", cost: 8 },
  { id: 80, name: "Hardik Pandya", team: "MI", category: "Indian", cost: 8 },
  { id: 81, name: "Jasprit Bumrah", team: "MI", category: "Indian", cost: 8 },
  { id: 82, name: "Tilak Varma", team: "MI", category: "Indian", cost: 8 },
  { id: 83, name: "Quinton de Kock", team: "MI", category: "Overseas", cost: 8 },
  { id: 84, name: "Trent Boult", team: "MI", category: "Overseas", cost: 8 },
  { id: 85, name: "Will Jacks", team: "MI", category: "Overseas", cost: 8 },
  { id: 86, name: "Mitchell Santner", team: "MI", category: "Overseas", cost: 8 },
  { id: 87, name: "Shardul Thakur", team: "MI", category: "Indian", cost: 8 },
  { id: 88, name: "Deepak Chahar", team: "MI", category: "Indian", cost: 8 },
  { id: 89, name: "Mayank Markande", team: "MI", category: "Indian", cost: 8 },
  { id: 90, name: "Sherfane Rutherford", team: "MI", category: "Overseas", cost: 8 },
  { id: 91, name: "Naman Dhir", team: "MI", category: "Indian", cost: 8 },
  { id: 92, name: "Ryan Rickelton", team: "MI", category: "Overseas", cost: 8 },

  // PBKS
  { id: 93, name: "Shreyas Iyer", team: "PBKS", category: "Indian", cost: 8 },
  { id: 94, name: "Prabhsimran Singh", team: "PBKS", category: "Indian", cost: 8 },
  { id: 95, name: "Shashank Singh", team: "PBKS", category: "Indian", cost: 8 },
  { id: 96, name: "Marcus Stoinis", team: "PBKS", category: "Overseas", cost: 8 },
  { id: 97, name: "Marco Jansen", team: "PBKS", category: "Overseas", cost: 8 },
  { id: 98, name: "Azmatullah Omarzai", team: "PBKS", category: "Overseas", cost: 8 },
  { id: 99, name: "Arshdeep Singh", team: "PBKS", category: "Indian", cost: 8 },
  { id: 100, name: "Yuzvendra Chahal", team: "PBKS", category: "Indian", cost: 8 },
  { id: 101, name: "Lockie Ferguson", team: "PBKS", category: "Overseas", cost: 8 },
  { id: 102, name: "Harpreet Brar", team: "PBKS", category: "Indian", cost: 8 },
  { id: 103, name: "Xavier Bartlett", team: "PBKS", category: "Overseas", cost: 8 },
  { id: 104, name: "Yash Thakur", team: "PBKS", category: "Indian", cost: 8 },
  { id: 105, name: "Vyshak Vijaykumar", team: "PBKS", category: "Indian", cost: 8 },
  { id: 106, name: "Vishnu Vinod", team: "PBKS", category: "Indian", cost: 8 },
  { id: 107, name: "Ben Dwarshuis", team: "PBKS", category: "Overseas", cost: 8 },

  // RR
  { id: 108, name: "Yashasvi Jaiswal", team: "RR", category: "Indian", cost: 8 },
  { id: 109, name: "Dhruv Jurel", team: "RR", category: "Indian", cost: 8 },
  { id: 110, name: "Riyan Parag", team: "RR", category: "Indian", cost: 8 },
  { id: 111, name: "Ravindra Jadeja", team: "RR", category: "Indian", cost: 8 },
  { id: 112, name: "Shimron Hetmyer", team: "RR", category: "Overseas", cost: 8 },
  { id: 113, name: "Dasun Shanaka", team: "RR", category: "Overseas", cost: 8 },
  { id: 114, name: "Donovan Ferreira", team: "RR", category: "Overseas", cost: 8 },
  { id: 115, name: "Jofra Archer", team: "RR", category: "Overseas", cost: 10 },
  { id: 116, name: "Sandeep Sharma", team: "RR", category: "Indian", cost: 8 },
  { id: 117, name: "Tushar Deshpande", team: "RR", category: "Indian", cost: 8 },
  { id: 118, name: "Ravi Bishnoi", team: "RR", category: "Indian", cost: 8 },
  { id: 119, name: "Adam Milne", team: "RR", category: "Overseas", cost: 8 },
  { id: 120, name: "Nandre Burger", team: "RR", category: "Overseas", cost: 8 },
  { id: 121, name: "Kuldeep Sen", team: "RR", category: "Indian", cost: 8 },
  { id: 122, name: "Shubham Dubey", team: "RR", category: "Indian", cost: 8 },

  // RCB
  { id: 123, name: "Virat Kohli", team: "RCB", category: "Indian", cost: 10 },
  { id: 124, name: "Rajat Patidar", team: "RCB", category: "Indian", cost: 8 },
  { id: 125, name: "Devdutt Padikkal", team: "RCB", category: "Indian", cost: 8 },
  { id: 126, name: "Phil Salt", team: "RCB", category: "Overseas", cost: 8 },
  { id: 127, name: "Jitesh Sharma", team: "RCB", category: "Indian", cost: 8 },
  { id: 128, name: "Tim David", team: "RCB", category: "Overseas", cost: 8 },
  { id: 129, name: "Romario Shepherd", team: "RCB", category: "Overseas", cost: 8 },
  { id: 130, name: "Krunal Pandya", team: "RCB", category: "Indian", cost: 8 },
  { id: 131, name: "Venkatesh Iyer", team: "RCB", category: "Indian", cost: 8 },
  { id: 132, name: "Josh Hazlewood", team: "RCB", category: "Overseas", cost: 8 },
  { id: 133, name: "Bhuvneshwar Kumar", team: "RCB", category: "Indian", cost: 10 },
  { id: 134, name: "Yash Dayal", team: "RCB", category: "Indian", cost: 8 },
  { id: 135, name: "Suyash Sharma", team: "RCB", category: "Indian", cost: 8 },
  { id: 136, name: "Nuwan Thushara", team: "RCB", category: "Overseas", cost: 8 },
  { id: 137, name: "Swapnil Singh", team: "RCB", category: "Indian", cost: 8 },

  // SRH
  { id: 138, name: "Abhishek Sharma", team: "SRH", category: "Indian", cost: 10 },
  { id: 139, name: "Ishan Kishan", team: "SRH", category: "Indian", cost: 8 },
  { id: 140, name: "Travis Head", team: "SRH", category: "Overseas", cost: 8 },
  { id: 141, name: "Heinrich Klaasen", team: "SRH", category: "Overseas", cost: 10 },
  { id: 142, name: "Nitish Kumar Reddy", team: "SRH", category: "Indian", cost: 8 },
  { id: 143, name: "Liam Livingstone", team: "SRH", category: "Overseas", cost: 8 },
  { id: 144, name: "Pat Cummins", team: "SRH", category: "Overseas", cost: 8 },
  { id: 145, name: "Kamindu Mendis", team: "SRH", category: "Overseas", cost: 8 },
  { id: 146, name: "Harshal Patel", team: "SRH", category: "Indian", cost: 8 },
  { id: 147, name: "Jaydev Unadkat", team: "SRH", category: "Indian", cost: 8 },
  { id: 148, name: "Shivam Mavi", team: "SRH", category: "Indian", cost: 8 },
  { id: 149, name: "Brydon Carse", team: "SRH", category: "Overseas", cost: 8 },
  { id: 150, name: "Zeeshan Ansari", team: "SRH", category: "Indian", cost: 8 },
  { id: 151, name: "Eshan Malinga", team: "SRH", category: "Overseas", cost: 10 },
  { id: 152, name: "David Payne", team: "SRH", category: "Overseas", cost: 8 }
];

module.exports = { teams, players, matches, stockPlayers };
